sudo: required
dist: trusty

language: c

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install cppcheck doxygen libssh-dev

install:
    - wget https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
    - tar xvf cmocka-1.1.0.tar.xz && pushd cmocka-1.1.0
    - mkdir build && pushd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
    - make
    - sudo make install
    - popd && popd

script:
    - scripts/cppcheck.sh
    - scripts/check-coding-style.sh
    - cmake -D CMAKE_BUILD_TYPE=NoSSH .
    - make
    - make test
    - make clean
    - cmake -D CMAKE_BUILD_TYPE=Release -DENABLE_COVERAGE=On -DUNIT_TESTING=On .
    - make
    - make test
    - make gcov

after_success:
  - bash <(curl -s https://codecov.io/bash)
